# Generated by Django 6.0 on 2026-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_trackcoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='album_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='trackcoment',
            name='album_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='trackcoment',
            name='track_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
