# Generated by Django 6.0 on 2026-03-12 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_comment_album_id_alter_trackcoment_album_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('author', 'album_id'), name='unique_user_album_comment'),
        ),
        migrations.AddConstraint(
            model_name='trackcoment',
            constraint=models.UniqueConstraint(fields=('author', 'track_id', 'album_id'), name='unique_user_track_album_comment'),
        ),
    ]
