# Generated by Django 6.0 on 2026-02-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyprofile',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
